### ISSUE TITLE
Remove "lightbulb" service

### ISSUE THREAD

**Issue by michaeltorbert** [aschaper/homebridge-airmega#2]
You can already turn it on and off via the fan accessory, so this seems redundant, and could negatively affect automations that turn on/off all the lights in the house.

**Comment by aschzero** [comment]
Hi @michaeltorbert, the separate light accessory is used to toggle the purifier lights independently so that the purifier can still be on and running with the lights turned off. However, I do see how the light accessory can be a hindrance in some cases.

I'll make a change to allow the option of excluding the light accessory and should have a new version available later today.

**Comment by michaeltorbert** [comment]
@aschzero Maybe I'm mixed up a bit... doesn't the light accessory toggle the purifier itself on/off?

**Comment by aschzero** [comment]
@michaeltorbert Actually no, the light accessory just toggles the lights on the purifier and nothing else. Toggling the light accessory is the same behavior as tapping the lightbulb button on the purifier itself.

**Comment by michaeltorbert** [comment]
@aschzero Yep, I just checked and you're absolutely right. Being able to exclude the light accessory would still be nice though.
Thanks so much for your work in creating this plugin.

**Comment by aschzero** [comment]
@michaeltorbert Of course! And thank you for your feedback; I'm glad you're finding the plugin useful!

I just pushed up homebridge-airmega@3.1.5 which adds the functionality to exclude the lightbulb accessory. You'll just have to update your config to include this line: `"exclude": ["lightbulb"]` so it'll look something like this:

```
{
  "platform": "Airmega",
  "username": "myusername",
  "password": "password123",
  "exclude": ["lightbulb"]
}
```

Please let me know if it works or if you happen to run into any issues. :)

**Comment by aschzero** [comment]
Closing this issue, please re-open if needed.
