### ISSUE TITLE
handling wifi button press

### ISSUE THREAD

**Issue by ohmantics** [aschaper/homebridge-airmega#3]
My 2 year old has taken to pressing the wifi button, which takes it offline. Pressing the button to go back online doesn't necessarily bring it back online in HomeKit. I found the following in the log:

`Nov 30 16:03:58 ha homebridge[11276]: [2018-11-30 16:03:58] [Airmega] [ERROR] Unable to update purifier status. TypeError: Cannot read property 'power' of undefined
Nov 30 16:03:58 ha homebridge[11276]: [2018-11-30 16:03:58] [Airmega] [ERROR] Unable to get active state. TypeError: Cannot read property 'power' of undefined
`

**Comment by aschzero** [comment]
Hi @ohmantics thanks for letting me know about this! I was able to identify the issue that caused the plugin to not be able to recover after a failed status update and just released an update (v3.1.6) to fix this. Please update when you can and let me know if the issue has been resolved. Thanks!

**Comment by aschzero** [comment]
Closing this issue, please re-open if needed.
