### ISSUE TITLE
“Inactive” sleep

### ISSUE THREAD

**Issue by paqpaqpaq** [aschaper/homebridge-airmega#5]
When I set the Airmega tot sleep mode with the app, homekit sets it to “Inactive”.

Would there be a way to initiate that state with the plugin? (Or sleep mode)

**Comment by aschzero** [comment]
Yep, the same behavior can be achieved by setting the mode to manual. With the Home app, long press the purifier accessory > tap Settings > tap "Manual" under the Mode section.

**Comment by paqpaqpaq** [comment]
Ah yes I see.
But only coming from Automatic. (correct?)

So there are more or less the following statuses:
- Automatic
- manual 1
- manual 2
- manual 3
- Inactive / sleep (Automatic > Manual)
- And then there is the state that Airmega will shut off the blower when set to Automatic and air is good for 10 mins.

I did find that when in Sleep (or Inactive for homekit) it doesn't switch back to a higher setting when you would trip the sensor.

I'm a but clueless all together though what this thing actually measures. I have a few air sensors near the Airmega and they often claim otherwise.

**Comment by aschzero** [comment]
Looking through the [Airmega manual (pdf)](https://www.cowaymega.com/wp-content/uploads/2018/02/Airmega_User_Manual.pdf), under "Smart Mode - ECO" it mentions that the purifier will shut off after 10 minutes of good air quality when the mode is set to auto. So I think that the first item and the last item in your list should be combined.

An important distinction I'd like to call out is that sleep mode will only turn the fan back on when poor air quality is detected only if the mode has been set to automatic. If the mode has been explicitly set to manual without a fan speed, it will remain in sleep mode until it's controlled again. So the list of modes would look more like:

* Automatic – adjusts fan speed based on air quality > sleeps after 10 minutes of good air quality > turns back on when poor air quality is detected
* Manual
    * Idle fan speed (this state is triggered when selecting "manual" mode in HomeKit) – remains in sleep mode until controlled again
    * Low fan speed 
    * Medium fan speed
    * High fan speed

Hopefully this answers your questions and I didn't create more confusion 😛

**Comment by aschzero** [comment]
Feel free to re-open if needed.
