### ISSUE TITLE
[ERROR] Unable to get current state. Cannot read property 'netStatus' of undefined

### ISSUE THREAD

**Issue by paqpaqpaq** [aschaper/homebridge-airmega#8]
Since yesterday, all of the sudden the Airmega IS being found at boot up, but shortly after returns this error.

Home app states: "no response"

**Comment by paqpaqpaq** [comment]
iOS update:

2.2.33Apr 24, 2019
Remove unnecessary permission requests
Multilingual support due to overseas launch
App store 6.5inch screenshot added

**Comment by aschzero** [comment]
It looks like they changed a few things in the API which broke the plugin, but thankfully the changes were pretty minor. I just published version `3.1.9` with the fixes, please update and let me know if you run into any other issues. Thanks for the report!

**Comment by paqpaqpaq** [comment]
> It looks like they changed a few things in the API which broke the plugin, but thankfully the changes were pretty minor. I just published version `3.1.9` with the fixes, please update and let me know if you run into any other issues. Thanks for the report!

thanks!

It's back up!
